version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    networks: 
      - overlay
    ports:
      - "27017:27017"
  app-dev:
    image: app:dev
    container_name: app-dev
    build:
      context: .
      dockerfile: Dockerfile
    command: dotnet HowYouFell.Api.dll 
    restart: always
    networks: 
      - overlay
    environment:
      - ASPNETCORE_HTTPS_PORT=433
      - Mongo__DatabaseName=${Mongo__DatabaseName}
      - Mongo__ConnectionString=${Mongo__ConnectionString}
      - Google__ProjectId=${Google__ProjectId}
      - App__AllowEmailsCreateTenant__0=${App__AllowEmailsCreateTenant__0}
    ports:
      - "5000:80"
    depends_on:
      - mongo
networks:
  overlay:
