global using Xunit;
global using HowYouFell.Api.Controllers;
global using HowYouFell.Api.Data;
global using HowYouFell.Api.Models;
global using HowYouFell.Api.Models.Inputs;
global using HowYouFell.Api.Services;
global using Moq.AutoMock;
global using Moq;
global using MongoDB.Driver;
global using Bogus;
global using Person = HowYouFell.Api.Models.Person;
global using Microsoft.AspNetCore.Http;
global using Microsoft.Extensions.Configuration;